name: coffee_house
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/banners/
  - assets/coffee/cafe-quente/
  - assets/coffee/cafe-gelado/
  - assets/coffee/cha-quente/
  - assets/coffee/cha-gelado/
  - assets/coffee/paes/
  - assets/coffee/suco/
  - assets/coffee/doces/
  - assets/coffee/milk-shakes/
  - assets/coffee/bebidas-veganas/
  - assets/coffee/agua/






