// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7HvW3JBkpHTUipM-bv3ZdHKOaymlKCDE',
    appId: '1:203655837390:web:78d0ff3f2d6d651c2f429f',
    messagingSenderId: '203655837390',
    projectId: 'coffeehouse-cbb97',
    authDomain: 'coffeehouse-cbb97.firebaseapp.com',
    storageBucket: 'coffeehouse-cbb97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFHR4HNdjjn8FVb1Hr9eRKbDjLIm9KfIs',
    appId: '1:203655837390:android:843e8ecaeb9be8fc2f429f',
    messagingSenderId: '203655837390',
    projectId: 'coffeehouse-cbb97',
    storageBucket: 'coffeehouse-cbb97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKFBmo9FzQpeOV3LCcrHT0wIH4er0KChk',
    appId: '1:203655837390:ios:6fc0e742297601332f429f',
    messagingSenderId: '203655837390',
    projectId: 'coffeehouse-cbb97',
    storageBucket: 'coffeehouse-cbb97.appspot.com',
    iosClientId: '203655837390-fovu2onknod1s0ev63h4n9b39vajh98c.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKFBmo9FzQpeOV3LCcrHT0wIH4er0KChk',
    appId: '1:203655837390:ios:6fc0e742297601332f429f',
    messagingSenderId: '203655837390',
    projectId: 'coffeehouse-cbb97',
    storageBucket: 'coffeehouse-cbb97.appspot.com',
    iosClientId: '203655837390-fovu2onknod1s0ev63h4n9b39vajh98c.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeHouse',
  );
}
